
services:
  postgres:
    image: postgres:16
    container_name: graphfy_db
    restart: on-failure:3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: graphfy_db
    ports:
      - "5432:5432"
    volumes:
    - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: